"""add active sessions table

Revision ID: 17026a9e059f
Revises: 188df6f48f91
Create Date: 2026-06-29 18:22:41.658368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17026a9e059f'
down_revision = '188df6f48f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.String(length=255), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tracked_portfolios', schema=None) as batch_op:
        batch_op.drop_index('ix_tracked_portfolios_user_id')
        batch_op.drop_index('ix_tracked_portfolios_username')

    op.drop_table('tracked_portfolios')
    op.drop_table('daily_digest_log')
    op.drop_table('prompt_likes')
    with op.batch_alter_table('portfolio_grades', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_grades_username')

    op.drop_table('portfolio_grades')
    with op.batch_alter_table('portfolio_histories', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_histories_username')

    op.drop_table('portfolio_histories')
    op.drop_table('saved_jobs')
    op.drop_table('prompts_backup_20260530')
    with op.batch_alter_table('agent_application_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_application_logs_fit_score'), ['fit_score'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_messages_user_id')

    with op.batch_alter_table('course_days', schema=None) as batch_op:
        batch_op.drop_index('idx_course_days_course_id')
        batch_op.create_index(batch_op.f('ix_course_days_course_id'), ['course_id'], unique=False)
        batch_op.create_unique_constraint('uq_course_day_number', ['course_id', 'day_number'])
        batch_op.create_unique_constraint('uq_course_day_slug', ['course_id', 'slug'])

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_index('idx_course_enrollments_course_id')
        batch_op.drop_index('idx_course_enrollments_user_id')
        batch_op.create_index(batch_op.f('ix_course_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_course_enrollment', ['user_id', 'course_id'])

    with op.batch_alter_table('daily_report_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('sent_at')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('idx_favorites_prompt_id')
        batch_op.drop_index('idx_favorites_user_id')
        batch_op.create_index(batch_op.f('ix_favorites_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.drop_column('budget')
        batch_op.drop_column('project_type')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_job_applications_job_id')
        batch_op.drop_index('idx_job_applications_user_id')
        batch_op.drop_constraint('unique_user_job_application', type_='unique')
        batch_op.create_index(batch_op.f('ix_job_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_job_application', ['user_id', 'job_id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('target_batch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'2025, 2026'::character varying"))
        batch_op.drop_column('embedding_json')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_progress_course_day_id')
        batch_op.drop_index('idx_lesson_progress_user_id')
        batch_op.drop_constraint('unique_completion_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_lesson_progress_course_day_id'), ['course_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_lesson_progress', ['user_id', 'course_day_id'])
        batch_op.drop_column('completion_email_sent')
        batch_op.drop_column('email_processing')

    with op.batch_alter_table('lesson_reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_reviews_course_day_id')
        batch_op.drop_index('idx_lesson_reviews_user_id')
        batch_op.create_index(batch_op.f('ix_lesson_reviews_course_day_id'), ['course_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_reviews_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_lesson_review', ['user_id', 'course_day_id'])

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('idx_prompts_user_id')
        batch_op.create_index(batch_op.f('ix_prompts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_view_count'), ['view_count'], unique=False)
        batch_op.drop_column('views')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('ai_model')

    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.drop_constraint('user_course_progress_user_course_unique', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_course_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_course_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_course_progress', ['user_id', 'course_id'])

    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_user_likes_prompt_id')
        batch_op.drop_index('idx_user_likes_user_id')

    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.drop_index('idx_user_memories_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_users_xp'), ['xp'], unique=False)
        batch_op.drop_column('welcome_email_sent')
        batch_op.drop_column('password_reset_token_hash')
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('welcome_email_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_xp'))
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.create_index('idx_user_memories_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.create_index('idx_user_likes_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_likes_prompt_id', ['prompt_id'], unique=False)

    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_course_progress', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_course_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_course_progress_course_id'))
        batch_op.create_unique_constraint('user_course_progress_user_course_unique', ['user_id', 'course_id'])

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_prompts_view_count'))
        batch_op.drop_index(batch_op.f('ix_prompts_user_id'))
        batch_op.create_index('idx_prompts_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('lesson_reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lesson_review', type_='unique')
        batch_op.drop_index(batch_op.f('ix_lesson_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_reviews_course_day_id'))
        batch_op.create_index('idx_lesson_reviews_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_lesson_reviews_course_day_id', ['course_day_id'], unique=False)

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_processing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completion_email_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_lesson_progress', type_='unique')
        batch_op.drop_index(batch_op.f('ix_lesson_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_course_day_id'))
        batch_op.create_unique_constraint('unique_completion_email', ['user_id', 'course_day_id'])
        batch_op.create_index('idx_lesson_progress_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_lesson_progress_course_day_id', ['course_day_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('target_batch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'2025, 2026'::character varying"))

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_job_application', type_='unique')
        batch_op.drop_index(batch_op.f('ix_job_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_job_id'))
        batch_op.create_unique_constraint('unique_user_job_application', ['user_id', 'job_id'])
        batch_op.create_index('idx_job_applications_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_job_applications_job_id', ['job_id'], unique=False)

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('budget', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_prompt_id'))
        batch_op.create_index('idx_favorites_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_favorites_prompt_id', ['prompt_id'], unique=False)

    with op.batch_alter_table('daily_report_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_enrollment', type_='unique')
        batch_op.drop_index(batch_op.f('ix_course_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_course_id'))
        batch_op.create_index('idx_course_enrollments_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_course_enrollments_course_id', ['course_id'], unique=False)

    with op.batch_alter_table('course_days', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_day_slug', type_='unique')
        batch_op.drop_constraint('uq_course_day_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_course_days_course_id'))
        batch_op.create_index('idx_course_days_course_id', ['course_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_messages_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('agent_application_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_application_logs_fit_score'))

    op.create_table('prompts_backup_20260530',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('copies', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('saved_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='saved_jobs_job_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_jobs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='saved_jobs_pkey'),
    sa.UniqueConstraint('user_id', 'job_id', name='unique_user_saved_job')
    )
    op.create_table('portfolio_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('public_repos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolio_histories_pkey')
    )
    with op.batch_alter_table('portfolio_histories', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_histories_username', ['username'], unique=False)

    op.create_table('portfolio_grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('punchline', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('bullet_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='portfolio_grades_pkey')
    )
    with op.batch_alter_table('portfolio_grades', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_grades_username', ['username'], unique=False)

    op.create_table('prompt_likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='prompt_likes_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='prompt_likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prompt_likes_pkey'),
    sa.UniqueConstraint('user_id', 'prompt_id', name='unique_prompt_like')
    )
    op.create_table('daily_digest_log',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('digest_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'digest_date', name='daily_digest_log_pkey')
    )
    op.create_table('tracked_portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_scanned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tracked_portfolios_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tracked_portfolios_pkey'),
    sa.UniqueConstraint('user_id', 'username', name='uq_user_tracked_portfolio')
    )
    with op.batch_alter_table('tracked_portfolios', schema=None) as batch_op:
        batch_op.create_index('ix_tracked_portfolios_username', ['username'], unique=False)
        batch_op.create_index('ix_tracked_portfolios_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_session_id'))

    op.drop_table('active_sessions')
    # ### end Alembic commands ###
