"""add AI job agent models

Revision ID: 188df6f48f91
Revises: 3fccdb63ac5a
Create Date: 2026-06-13 23:14:33.212452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '188df6f48f91'
down_revision = '3fccdb63ac5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_job_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.String(length=500), nullable=False),
    sa.Column('recruiter_email', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apply_url')
    )
    op.create_table('agent_application_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('drafted_subject', sa.String(length=300), nullable=True),
    sa.Column('drafted_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_opportunity_id'], ['agent_job_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_opportunity_id', name='uq_user_job_opportunity')
    )
    op.create_table('user_agent_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('target_roles', sa.String(length=300), nullable=True),
    sa.Column('target_locations', sa.String(length=300), nullable=True),
    sa.Column('min_salary', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agent_configs')
    op.drop_table('agent_application_logs')
    op.drop_table('agent_job_opportunities')
    # ### end Alembic commands ###
